-- Run this in Supabase SQL Editor before enabling SUPABASE_* env vars.

create table if not exists foods (
  id bigint generated by default as identity primary key,
  name text not null,
  calories_per_serving double precision not null,
  serving_size text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists foods_name_lower_idx on foods (lower(name));

create table if not exists daily_logs (
  id bigint generated by default as identity primary key,
  user_id text not null,
  food_id bigint references foods(id) on delete set null,
  food_name text not null,
  calories_consumed double precision not null,
  servings double precision not null default 1,
  log_date date not null,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);

create index if not exists daily_logs_user_date_idx on daily_logs (user_id, log_date);
create index if not exists daily_logs_user_food_idx on daily_logs (user_id, food_id);
create index if not exists daily_logs_user_foodname_idx on daily_logs (user_id, lower(food_name));

create table if not exists health_sync (
  id bigint generated by default as identity primary key,
  user_id text not null,
  sync_date date not null,
  total_calories_consumed double precision not null,
  total_calories_burned double precision not null,
  deficit double precision not null,
  source text not null default 'apple_health',
  synced_at timestamptz not null default now(),
  unique (user_id, sync_date)
);

create index if not exists health_sync_user_date_idx on health_sync (user_id, sync_date);

create table if not exists frequent_foods (
  id bigint generated by default as identity primary key,
  user_id text not null,
  food_id bigint references foods(id) on delete set null,
  food_name text,
  calories_per_serving double precision,
  log_count integer not null default 0,
  last_logged_at timestamptz not null default now()
);

create index if not exists frequent_foods_user_idx on frequent_foods (user_id);
create index if not exists frequent_foods_user_foodid_idx on frequent_foods (user_id, food_id);
create index if not exists frequent_foods_user_foodname_idx on frequent_foods (user_id, lower(food_name));

create table if not exists weekly_summary (
  id bigint generated by default as identity primary key,
  user_id text not null,
  week_start_date date not null,
  total_calories_consumed double precision not null,
  total_calories_burned double precision not null,
  total_deficit double precision not null,
  average_daily_deficit double precision not null,
  generated_at timestamptz not null default now(),
  unique (user_id, week_start_date)
);
